-- Seed data for products
INSERT INTO products (product_id, supplier_id, name, description, price, sku, unit, img_name, discount) VALUES 
(1, 3, 'Smart Savings Account', 'AI-powered savings account that learns your spending patterns and automatically saves based on your financial goals. Detects overspending, optimizes savings rates, and provides financial health insights.', 0.00, 'BANK-SAVE-001', 'account', 'feeder.png', 0.25),
(2, 3, 'Premium Checking Account', 'A full-featured checking account that detects patterns in your spending habits. Sends you financial reports and mobile alerts for unusual transactions.', 15.99, 'BANK-CHECK-001', 'monthly', 'litter-box.png', 0.25),
(3, 2, 'Investment Portfolio Manager', 'AI-driven investment platform with personalized portfolio recommendations. Think robo-advisor, but smarter - customized investment strategies based on your risk tolerance and goals.', 89.99, 'BANK-INVEST-001', 'monthly', 'catflix.png', 0.0),
(4, 2, 'Credit Monitoring Service', 'Real-time credit score tracking with AI-powered financial health detection. Monitors credit patterns, spending behavior, and provides personalized improvement recommendations.', 29.99, 'BANK-CREDIT-001', 'monthly', 'smart-collar.png', 0.0),
(5, 1, 'Business Banking Suite', 'Comprehensive business banking solution that adapts to your company''s financial cycles. Auto-generates financial reports, manages cash flow, and provides business insights.', 149.99, 'BANK-BIZ-001', 'monthly', 'sleep-nest.png', 0.15),
(6, 1, 'Personal Finance Assistant', 'AI-powered financial advisor that analyzes your spending, detects opportunities for savings, and provides personalized budgeting recommendations with goal tracking.', 19.99, 'BANK-ADVISOR-001', 'monthly', 'auto-groomer.png', 0.0),
(7, 1, 'Premium Investment Package', 'Advanced investment management with dedicated advisor, portfolio rebalancing, and tax optimization strategies. Designed for high-net-worth individuals.', 299.99, 'BANK-PREMIUM-001', 'monthly', 'scratch-pad.png', 0.10),
(8, 2, 'Mobile Banking Plus', 'Advanced mobile banking app with biometric security, real-time transaction notifications, and AI-powered spending insights. Includes budgeting tools and financial goal tracking.', 9.99, 'BANK-MOBILE-001', 'monthly', 'smart-fountain.png', 0.0),
(9, 3, 'Wealth Management Service', 'Comprehensive wealth management with AI-driven portfolio optimization, estate planning, and tax strategy consultation. Professional service for building long-term wealth.', 399.99, 'BANK-WEALTH-001', 'monthly', 'auto-groomer.png', 0.20),
(10, 1, 'Retirement Planning Pro', 'Advanced retirement planning service with personalized investment strategies and regular portfolio reviews. Includes retirement income planning and tax optimization.', 179.99, 'BANK-RETIRE-001', 'monthly', 'sleep-nest.png', 0.0),
(11, 3, 'Digital Wallet Pro', 'Smart digital payment solution with biometric security and transaction categorization. Tracks spending patterns and provides insights to your financial dashboard.', 12.99, 'BANK-WALLET-001', 'monthly', 'door-dash.png', 0.0),
(12, 2, 'Financial Analytics Dashboard', 'Comprehensive financial tracking platform that monitors all your accounts, analyzes spending trends, and generates detailed financial health reports.', 39.99, 'BANK-ANALYTICS-001', 'monthly', 'tracker-mat.png', 0.0);